{% set name = "docspec" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/docspec-{{ version }}.tar.gz
  sha256: 5206c061d2c0171add8412028a79b436acc87786cfc582aeda341beda81ae582

build:
  number: 1
  noarch: python
  entry_points:
    - docspec = docspec.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - databind.core >=1.0.0,<2.0.0
    - databind.json >=1.0.0,<2.0.0
    - python >={{ python_min }},<4.0

test:
  imports:
    - docspec
  commands:
    - pip check
    - docspec --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/docspec/
  summary: Docspec is a JSON object specification for representing API documentation of programming languages.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
